### ISSUE TITLE
我想问怎么给 swoole 扩展 配置  --enable-openssl 

### ISSUE THREAD

**Issue by yemaozi999** [Tinywan/dnmp#2]
![image](https://github.com/Tinywan/dnmp/assets/16147749/e1c8c97d-88d1-4466-a651-1340adfc5b65)
我的系统版本 是 alpine3.13   应该是安装的,   还是不是走这里的配置的

**Comment by yemaozi999** [comment]
![image](https://github.com/Tinywan/dnmp/assets/16147749/c4b811e8-8b65-4616-9635-9c80cbb66d65)

**Comment by Tinywan** [comment]
构建不行？

**Comment by yemaozi999** [comment]
![image](https://github.com/Tinywan/dnmp/assets/16147749/000b696e-bfbd-429c-a32e-ac7591131ae7)
可能我写错了, 我试试改成这样
